### ISSUE TITLE
如何在本地跑

### ISSUE THREAD

**Issue by Roen-Ro** [sorz/asstosrt-wasm#2]
我不是做前端的，但是想用你写的这套代码在本地运行来进行批量字幕处理；
我在下载你的代码里面找到index.html用浏览器打开，打开后可以选择文件，但是选择文件后不能自动转换，请问这是bug还是我不懂操作

**Comment by sorz** [comment]
你可以尝试下载 [gh-pages branch](https://github.com/sorz/asstosrt-wasm/tree/gh-pages/) 中的代码，里面有编译好的文件。

**Comment by Goooooooooood** [comment]
本程序无法运行在纯静态环境，应该是你的web-server环境没有配置对，缺乏对控件的支持。

几年前就看到你的提问了，那会儿我一直懒得注册github账号，所以没法回答你。

我还对这个项目做了汉化，在我的Apache服务器运行了几年，自己用确实很方便。

希望对后来者有帮助。
